version: '3.8'

services:
  bot:
    build: .
    container_name: my-weather-bot
    restart: always
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: bot-cache
    restart: always